In [24]:
import numpy as np
np.set_printoptions(precision=2, suppress=True)

In [25]:
NUM_ROWS = 4
NUM_COLUMNS = 3
STEP_COST = -0.04
GAMMA = 0.95

In [26]:
W = [ (2, 1) ]
T = [ (2, 1), (0, 1), (0, 2) ]

In [27]:
def is_valid(
    state: (int, int)
) -> bool:

    row = state[0]
    col = state[1]

    if not 0 <= row < NUM_ROWS:
        return False

    if not 0 <= col < NUM_COLUMNS:
        return False

    if state in W:
        return False

    return True

In [28]:
def generate_actions(
    row: int,
    col: int,
    p: float
) -> dict[str, dict[(int, int), float]]:

    acc = p
    fail = (1 - p) / 2

    actions = {}
    actions['up'] = { (row - 1, col): acc, (row, col - 1): fail, (row, col + 1): fail }
    actions['down'] = { (row + 1, col): acc, (row, col - 1): fail, (row, col + 1): fail }
    actions['left'] = { (row, col - 1): acc, (row - 1, col): fail, (row + 1, col): fail }
    actions['right'] = { (row, col + 1): acc, (row - 1, col): fail, (row + 1, col): fail }

    return constrain_actions(row, col, actions)

In [29]:
def constrain_actions(
    row: int,
    col: int,
    actions: dict[str, dict[(int, int), float]]
) -> dict[str, dict[(int, int), float]]:

    actions_new = {}
    for action, transition in actions.items():
        residue = 0
        transitions_new = {}
        for state, prob in transition.items():
            if is_valid(state):
                transitions_new[state] = prob
            else:
                residue += prob
        if residue != 0:
            transitions_new[(row, col)] = residue
        actions_new[action] = transitions_new

    return actions_new

In [30]:
def evaluate_actions(
    U: list[list[int]],
    actions: dict[str, dict[(int, int), float]]
) -> dict[str, float]:

    evals = {}
    for action, transition in actions.items():
        value = 0
        for state, prob in transition.items():
            value += prob * U[state[0]][state[1]]
        evals[action] = value

    return evals

In [31]:
def optimal_action(
    evals: dict[str, float]
) -> (str, float):

    opt_value = -1e30
    opt_strategy = None
    for strategy, value in evals.items():
        if value > opt_value:
            opt_value = value
            opt_strategy = strategy

    return opt_strategy, opt_value

In [32]:
def value_iteration(
    p: float,
    log: bool = False
) -> (np.ndarray, np.ndarray):

    U = np.zeros((NUM_ROWS, NUM_COLUMNS))
    P = np.full((NUM_ROWS, NUM_COLUMNS), 'none', dtype='object') 
    U[0][1] = -1
    U[0][2] = 1

    k = 0
    while True:
        U_new = np.copy(U)
        P_new = np.copy(P)

        for i, U_i in enumerate(U):
            for j, U_ij in enumerate(U_i):
                if (i, j) not in T:
                    actions = generate_actions(i, j, p)
                    evals = evaluate_actions(U, actions)
                    action, val = optimal_action(evals)
                    U_new[i][j] = STEP_COST + GAMMA * val
                    P_new[i][j] = action

        if (np.absolute(U_new - U) <= 1e-4).all():
            break
        if log:
            print(U_new, end='\n\n')

        k = k + 1
        U = U_new
        P = P_new

    return U, P

In [33]:
utility, policy = value_iteration(0.7, log=True)

[[-0.04 -1.    1.  ]
 [-0.04 -0.04  0.62]
 [-0.04  0.   -0.04]
 [-0.04 -0.04 -0.04]]

[[-0.08 -1.    1.  ]
 [-0.08  0.23  0.71]
 [-0.08  0.    0.36]
 [-0.08 -0.08 -0.08]]

[[-0.11 -1.    1.  ]
 [ 0.09  0.32  0.76]
 [-0.11  0.    0.53]
 [-0.11 -0.11  0.18]]

[[-0.12 -1.    1.  ]
 [ 0.14  0.37  0.78]
 [-0.01  0.    0.62]
 [-0.15  0.05  0.33]]

[[-0.11 -1.    1.  ]
 [ 0.19  0.39  0.79]
 [ 0.05  0.    0.65]
 [-0.03  0.19  0.42]]

[[-0.07 -1.    1.  ]
 [ 0.21  0.4   0.79]
 [ 0.1   0.    0.67]
 [ 0.09  0.3   0.48]]

[[-0.05 -1.    1.  ]
 [ 0.23  0.4   0.79]
 [ 0.13  0.    0.68]
 [ 0.18  0.36  0.52]]

[[-0.04 -1.    1.  ]
 [ 0.24  0.4   0.8 ]
 [ 0.15  0.    0.68]
 [ 0.25  0.41  0.54]]

[[-0.03 -1.    1.  ]
 [ 0.24  0.4   0.8 ]
 [ 0.17  0.    0.68]
 [ 0.29  0.43  0.55]]

[[-0.02 -1.    1.  ]
 [ 0.25  0.4   0.8 ]
 [ 0.2   0.    0.68]
 [ 0.31  0.45  0.55]]

[[-0.02 -1.    1.  ]
 [ 0.25  0.4   0.8 ]
 [ 0.22  0.    0.68]
 [ 0.33  0.46  0.56]]

[[-0.02 -1.    1.  ]
 [ 0.26  0.4   0.8 ]
 [ 0.24  0. 

In [34]:
for i in range(1, 10):
    p = i / 10
    utility, policy = value_iteration(p)
    print('p =', p)
    print(utility)
    print(policy)
    print()

p = 0.1
[[ 0.08 -1.    1.  ]
 [ 0.18  0.32  0.59]
 [ 0.02  0.    0.33]
 [-0.04  0.04  0.22]]
[['left' 'none' 'none']
 ['up' 'down' 'right']
 ['left' 'none' 'left']
 ['up' 'up' 'right']]

p = 0.2
[[-0.02 -1.    1.  ]
 [ 0.08  0.25  0.55]
 [-0.06  0.    0.28]
 [-0.09 -0.02  0.16]]
[['left' 'none' 'none']
 ['up' 'down' 'right']
 ['left' 'none' 'left']
 ['up' 'up' 'right']]

p = 0.3
[[-0.08 -1.    1.  ]
 [ 0.03  0.23  0.58]
 [-0.06  0.    0.38]
 [-0.04  0.07  0.22]]
[['left' 'none' 'none']
 ['down' 'down' 'right']
 ['left' 'none' 'up']
 ['down' 'right' 'right']]

p = 0.4
[[-0.14 -1.    1.  ]
 [-0.02  0.2   0.59]
 [-0.08  0.    0.43]
 [-0.01  0.13  0.25]]
[['left' 'none' 'none']
 ['down' 'down' 'right']
 ['left' 'none' 'up']
 ['down' 'right' 'right']]

p = 0.5
[[-0.1  -1.    1.  ]
 [ 0.05  0.24  0.64]
 [ 0.    0.    0.51]
 [ 0.09  0.23  0.33]]
[['left' 'none' 'none']
 ['right' 'down' 'up']
 ['down' 'none' 'up']
 ['right' 'right' 'up']]

p = 0.6
[[-0.05 -1.    1.  ]
 [ 0.14  0.29  0.72]
 [ 0

### Analysis of Policy

- In case of high accuracy in actions, i.e. high value of p, the policy is directed towards the path leading to the reward state. The bottom-left state, i.e. (3, 0) which has two paths to reach the same, prefers the one that avoids moving close to the penalty state. The same is noticed with (2, 0) as p decreases slightly.

- As the accuracy drops below a certain threshold, the value iteration method adopts a precautious mindset that weighs higher the odds of falling into the penalty state. This can be observed with the states (0, 0) and (1, 1), that prescribe action exactly opposite to the penalty state, resulting in zero probability of transitioning to the penalty state. With further drop, (1, 0) and (2, 0) also follow suit.

- When inaccurate movements start to dominate, i.e. the probability of perpendicular movements shoot up, we notice the policy starts prescribing actions perpendicular to what it suggested earlier. For example, the state below the reward state, i.e. (1, 2) suggests moving right as the optimal action, instead of the perpendicular up. Similarly, the bottom-left state, i.e. (3, 0) suggests moving up, instead of right.